### PR TITLE
Support unicode range

### PR DESCRIPTION
**Pull request by xiejiangzhi**
for example: 
```
/[\u4e00-\u9fa5]{2,4}/.random_example 
# => "廢仅弙"
```

### CODE REVIEW

**Comment by xiejiangzhi** [comment]
The CI is failed before my changes.

**Comment by tom-lord** [comment]
CI should be fixed now, sorry.
I think we should add `spec/examples.txt` to the `.gitignore` before merging; I'll look through these change more carefully later if CI goes green.

Thanks for the contribution 😃

**Comment by xiejiangzhi** [comment]
Hi @tom-lord , I removed `spec/examples.txt`.

**Comment by tom-lord** [comment]
:+1: Thanks!

**Pull request merged**
